version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hvault-access"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9fou2d3kako8"
s3_prefix = "hvault-access"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

