AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Sample App to access Hashicorp Vault using assumed role
Parameters:
  VaultAccountId:
    Description: Please provide the Vault Account Id
    Type: String
    Default: 951145066533
  VaultAddr:
    Description: Please provide the Vault endpoint
    Type: String
    Default: https://ec2-18-204-7-79.compute-1.amazonaws.com:8200
  VaultNamespace:
    Description: Please provide the Vault Namespace
    Type: String
    Default: ccenter
  VaultCert:
    Description: Please provide the Vault SSL Certification Chain location
    Type: String
    Default: https://aws-sam-cli-managed-default-samclisourcebucket-9fou2d3kako8.s3.amazonaws.com/certs/vault-cert.pem
  VaultSkipVerify:
    Description: Whether to trust un-verified certificates
    Type: String
    Default: true
  VaultRoleArn:
    Description: VaultRoleToTrust
    Type: String
    Default: arn:aws:iam::951145066533:role/VaultRole_Opt3_CCDev

Globals:
  Function:
    Timeout: 5

Resources:
  HVaultOpt12FunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: HVaultOpt12FunctionRole
      Tags:
        - Key: 'vault-access'
          Value: !Ref VaultAccountId
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
              AWS: !Sub
                - arn:aws:iam::${vaultaccountid}:root
                - { vaultaccountid: !Ref VaultAccountId}
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: vault_policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: iam:GetRole
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/HVaultOpt12FunctionRole'
              - Effect: Allow
                Action: sts:GetCallerIdentity
                Resource: '*'
  HVaultOpt3FunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: HVaultFOpt3unctionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: !Ref VaultRoleArn
  HVaultAccessFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hvault_function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          VAULT_ADDR: !Ref VaultAddr
          VAULT_SERVER_CERT: !Ref VaultCert
          VAULT_SKIP_VERIFY: !Ref VaultSkipVerify
          VAULT_NAMESPACE: !Ref VaultNamespace
          VAULT_AWS_REGION: !Ref "AWS::Region"
      FunctionName: HVaultAccessFunctionOpt12
      Events:
        HVaultAccess:
          Type: Api
          Properties:
            Path: /hvault
            Method: get
      Role: !GetAtt HVaultOpt12FunctionIamRole.Arn
Outputs:
  HVaultAccessApi:
    Description: "API Gateway endpoint URL for Prod stage for Hashicorp Vault Access"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hvault"
  HVaultAccessFunction:
    Description: "Hashicorp Vault Lambda Function ARN"
    Value: !GetAtt HVaultAccessFunction.Arn
  HVaultOpt3FunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HVaultOpt3FunctionIamRole.Arn
